---
title: Airbag Industries
baseURL: https://localhost:1313/
params:
  author: Greg Storey
  description: Airbag has been around since Moveabletype Beta and has enjoyed a reputation
    for being a blunt voice in the world of digital design.
  images:
  - "/assets/img/default.jpg"
  DateForm: 2 January '06
  languageCode: en-us
permalinks:
  post: "/:filename/"
menu:
  navlinks:
  - url: "/archive"
    name: Archive
    weight: 5
    identifier: archive
  - url: "/contact"
    name: Contact
    weight: 4
    identifier: contact
  - url: "/about"
    name: About
    weight: 2
    identifier: about
  - url: "/"
    name: Home
    weight: 1
    identifier: home
  - url: https://airbagindustries.com/index.xml
    name: Subscribe
    weight: 3
    identifier: subscribe
  worklinks:
  - url: https://www.linkedin.com/in/brilliantcrank
    name: LinkedIn
    weight: 1
  - url: https://storey.myportfolio.com
    name: Portfolio
    weight: 2
  sociallinks:
  - url: https://medium.com/@Brilliantcrank
    name: Medium
    weight: 4
  - url: https://www.playstation.com/en-us/my/public-trophies/?onlinename=Brilliantcrank
    name: Playstation
    weight: 6
  - url: https://twitter.com/Brilliantcrank
    name: Twitter
    weight: 1
  - url: https://instagram.com/Brilliantcrank
    name: Instagram
    weight: 2
  - url: https://www.flickr.com/photos/brilliantcrank
    name: Flickr
    weight: 3
  - url: https://www.dribbble.com/players/Brilliantcrank
    name: Dribbble
    weight: 5
