title: Airbag Industries
baseURL: https://localhost:1313/

params:
  author: Greg Storey
  description: A blunt voice in the world of interactive design.
  images:
  - /assets/img/default.jpg
  DateForm: "2 January '06"
  languageCode: en-us

permalinks:
  post: /archive/:filename/

menu:
  navlinks:
  - identifier: subscribe
    name: Subscribe
    url: https://feeds.feedburner.com/airbag
    weight: 5
  sociallinks:
  - name: Twitter
    url: 'https://twitter.com/Brilliantcrank'
  - name: Instagram
    url: 'https://instagram.com/Brilliantcrank'
  - name: Medium
    url: 'https://medium.com/@Brilliantcrank'
  - name: Flickr
    url: 'https://www.flickr.com/photos/brilliantcrank'
  - name: Dribbble
    url: 'https://www.dribbble.com/players/Brilliantcrank'
  - name: Playstation
    url: 'https://www.playstation.com/en-us/my/public-trophies/?onlinename=Brilliantcrank'
  worklinks:
  - name: LinkedIn
    url: https://www.linkedin.com/in/brilliantcrank
  - name: Resume
    url: https://www.linkedin.com/in/brilliantcrank
