title: Airbag Industries
baseURL: http://localhost:1313/

params:
  author: Greg Storey
  description: Airbag has been around since Moveabletype beta and has enjoyed a reputation for being a blunt voice in the world of interactive design.
  images:
  - /assets/img/default.jpg
  DateForm: "2 January '06"
  languageCode: en-us
  
permalinks:
  post: /:filename/

menu:
  navlinks:
  - identifier: subscribe
    name: Subscribe
    url: http://feeds.feedburner.com/airbag
    weight: 5
  sociallinks:
  - name: Twitter
    url: 'http://twitter.com/Brilliantcrank'
  - name: Instagram
    url: 'http://instagram.com/Brilliantcrank'
  - name: Medium
    url: 'https://medium.com/@Brilliantcrank'
  - name: Flickr
    url: 'http://www.flickr.com/photos/brilliantcrank'
  - name: Dribbble
    url: 'http://www.dribbble.com/players/Brilliantcrank'
  - name: Playstation
    url: 'https://www.playstation.com/en-us/my/public-trophies/?onlinename=Brilliantcrank'
  worklinks:
  - name: LinkedIn
    url: https://www.linkedin.com/in/brilliantcrank
  - name: Resume
    url: /resume/gregstorey.pdf