# Config for Netlify

# Redirect for legacy permalinks
[[redirects]]
  from = "/archives/airbag/*.php"
  to = "/:splat"

# Test redirect
[[redirects]]
  from = "/foo/"
  to = "/archive/"

# Test redirect 2
[[redirects]]
  from = "/foobar/*"
  to = "/:splat"