# Config for Netlify

# Redirect for legacy permalinks
[[redirects]]
  from = "/archives/airbag/*.php"
  to = "/:splat"

# Redirect for legacy media
[[redirects]]
  from = "/bucket/*"
  to = "/uploads/:splat"
[[redirects]]
  from = "/images/*"
  to = "/uploads/:splat"

# Test redirect
[[redirects]]
  from = "/foo/"
  to = "/archive/"

# Test redirect 2
[[redirects]]
  from = "/foobar/*"
  to = "/:splat"