---
label: Article
hide_body: false
fields:
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Meta Description
  description: Custom meta description, used for search and social summaries
- name: date
  type: datetime
  label: Date
  description: Publish date
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
