---
label: Article
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Article title, appears at the top of the article and in the HTML title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Meta Description
  description: Custom meta description, used for search and social summaries
- name: date
  type: datetime
  label: Date
  description: Publish date
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- content/post/i-m-attending-the-society-of-news-design-annual-conference-in-dc-and-i-can-t-hold-my-pee.md
- content/post/the-future-of-the-web-design-agency-in-the-united-states.md
- content/post/we-are-losing-the-history-of-web-design.md
- content/post/and-they-all-look-just-the-same.md
- content/post/pick-up-the-phone.md
- content/post/so-not-very-cool.md
- content/post/we-could-have-saved-eden-but-the-1-1-will-suffice.md
- content/post/twenty-years-apart.md
- content/post/i-made-an-internet-radio-program-and-it-s-called-sprints-milestones.md
- content/post/kitchen-storey-has-left-the-airport.md
- content/post/adios-muchachos-and-thanks-for-all-of-the-sun-downs.md
