---
label: Article
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Article title, appears at the top of the article and in the HTML title
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Meta Description
  description: Custom meta description, used for search and social summaries
- name: date
  type: datetime
  label: Date
  description: Publish date
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- content/post/we-could-have-saved-eden-but-the-1-1-will-suffice.md
- content/post/kitchen-storey-has-left-the-airport.md
- content/post/i-made-an-internet-radio-program-and-it-s-called-sprints-milestones.md
- content/post/adios-muchachos-and-thanks-for-all-of-the-sun-downs.md
- content/post/twenty-years-apart.md
- content/post/trusting-your-way-to-a-better-design-team.md
- content/post/medium-vs-the-self-hosted-blog.md
- content/post/the-new-macbook-pro-the-one-without-the-touchbar-is-pretty-great-1.md
- content/post/and-they-all-look-just-the-same.md
- content/post/pick-up-the-phone.md
- content/post/a-comprehensive-well-considered-list-of-things-designers-simply-can-t-do.md
- content/post/we-are-losing-the-history-of-web-design.md
- content/post/the-future-of-the-web-design-agency-in-the-united-states.md
- content/post/i-m-attending-the-society-of-news-design-annual-conference-in-dc-and-i-can-t-hold-my-pee.md
- content/post/you-are-not-your-job-search.md
- content/post/making-sense-of-all-the-jibba-jabba-during-user-research-1.md
- content/post/dealing-with-an-absent-decision-maker-during-times-of-review.md
- content/post/an-unexpected-worldwide-turn-1.md
- content/post/a-better-way-to-make-better-forms.md
- content/post/we-re-publishing-a-cultural-print-magazine-at-work-you-should-too.md
- content/post/now-serving-those-whom-serve.md
- content/post/goodbye-big-blue.md
- content/post/don-t-hire-the-person-in-front-of-you-hire-the-person-you-re-going-to-help-them-become.md
- content/post/100-clever-0-hired.md
- content/post/never-write-a-contract-using-cut-and-paste.md
- content/post/stay-on-target-no-one-forgets-a-designer-who-quits.md
- content/post/steve-austin.md
