---
label: Longboard
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Link title, appears on the home page list
- name: target_url
  type: text
  config:
    required: true
  label: Target URL
  description: External URL this post will link to.
- name: date
  type: datetime
  description: Publish date
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  label: Date
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/longboard/the-fifty-most-important-websites-of-all-time.md
- content/longboard/ibm-smacks-down-google-on-it-s-claim-around-quantum-computing.md
- content/longboard/i-took-the-world-s-first-20-hour-flight-here-s-what-it-did-to-me.md
- content/longboard/stories-of-people-who-are-racing-to-save-us.md
- content/longboard/fontshop-is-celebrating-30-years-in-business-with-a-30-discount-on-particular-font-families.md
