---
label: Longboard
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Link title, appears on the home page list
- name: target_url
  type: text
  config:
    required: true
  label: Target URL
  description: External URL this post will link to.
- name: date
  type: datetime
  description: Publish date
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  label: Date
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/longboard/according-to-20-000-creatives-brainstorming-is-a-giant-waste-of-time.md
- content/longboard/atari-is-now-a-brand-of-hotels.md
- content/longboard/fontshop-is-celebrating-30-years-in-business-with-a-30-discount-on-particular-font-families.md
- content/longboard/helping-greg-story-get-airbag-industries-off-movable-type-and-onto-a-better-publishing-stack.md
- content/longboard/how-airships-could-return-to-our-crowded-skies.md
- content/longboard/i-took-the-world-s-first-20-hour-flight-here-s-what-it-did-to-me.md
- content/longboard/ibm-smacks-down-google-on-it-s-claim-around-quantum-computing.md
- content/longboard/in-u-s-library-visits-outpaced-trips-to-movies-in-2019.md
- content/longboard/is-it-canceled-yet.md
- content/longboard/professional-wisdom-from-one-of-the-best-enterprise-grade-senior-designers-i-know.md
- content/longboard/python-movin-on-up.md
- content/longboard/solari-boards-the-disappearing-sound-of-airports.md
- content/longboard/stories-of-people-who-are-racing-to-save-us.md
- content/longboard/the-fifty-most-important-websites-of-all-time.md
- content/longboard/the-highlighter-of-1484.md
- content/longboard/typographic-illusions.md
- content/longboard/what-happens-to-a-society-that-loses-its-capacity-for-awe-and-wonder-at-things-to-come.md
