---
label: Longboard
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Link title, appears on the home page list
- name: target_url
  type: text
  config:
    required: true
  label: Target URL
  description: External URL this post will link to.
- name: date
  type: datetime
  description: Publish date
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  label: Date
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/longboard/000000-lives-matter-1.md
- content/longboard/000000-lives-matter.md
- content/longboard/500-versus-16-steak-dinner.md
- content/longboard/a-comprehensive-look-at-the-energy-crisis-nobody-saw-coming.md
- content/longboard/a-conversation-with-the-graphic-designer-who-until-his-death-at-91-was-still-thinking-about-how-his-craft-could-help-his-beleaguered-city..md
- content/longboard/a-farewell-to-the-quick-brown-fox..md
- content/longboard/according-to-20-000-creatives-brainstorming-is-a-giant-waste-of-time.md
- content/longboard/after-three-years-of-data-analysis-the-discrepancy-remains-a-potential-sign-of-new-physics.md
- content/longboard/an-event-apart-just-launched-its-first-virtual-event-human-centered-design.md
- content/longboard/an-oral-history-behind-the-star-trek-episode-that-saved-next-generation.md
- content/longboard/an-oral-history-of-the-birth-of-responsive-web-design.md
- content/longboard/apple-keynote-animation-masterclass.md
- content/longboard/atari-is-now-a-brand-of-hotels.md
- content/longboard/boba-fett-will-appear-in-the-next-season-of-the-mandalorian.md
- content/longboard/boot-camp-will-not-work-on-apple-silicon-based-macs..md
- content/longboard/convincing-looking-90s-fonts-in-modern-browsers.md
- content/longboard/diamond-comics-distributors-announced-that-it-will-cease-shipping-new-comics-as-of-this-week.md
- content/longboard/every-jurassic-park-dinosaur-illustrated-with-modern-science.md
- content/longboard/every-zoom-security-and-privacy-flaw-so-far-and-what-you-can-do-to-protect-yourself.md
- content/longboard/five-typography-adjacent-books-for-indoor-times.md
- content/longboard/fontshop-is-celebrating-30-years-in-business-with-a-30-discount-on-particular-font-families.md
- content/longboard/four-principles-from-a-working-mom-worth-applying-to-all-of-our-lives.md
- content/longboard/graphic-design-is-usually-used-to-amplify-a-desired-effect.as-such-when-successful-typography-changes-perception.this-is-not-easy-to-quantify-but-we-know-that-it-happens..md
- content/longboard/helping-greg-story-get-airbag-industries-off-movable-type-and-onto-a-better-publishing-stack.md
- content/longboard/hoefler-co-goes-on-the-campaign-trail.md
- content/longboard/how-airships-could-return-to-our-crowded-skies.md
- content/longboard/how-do-you-communicate-to-people-ten-thousand-years-from-now.md
- content/longboard/how-to-hug-during-a-pandemic.md
- content/longboard/how-to-play-dungeons-dragons-and-other-pen-and-paper-games-without-leaving-home.md
- content/longboard/how-to-take-a-decent-photo-of-your-own-shoes-with-a-combination-of-iphone-and-apple-watch.md
- content/longboard/i-m-going-to-need-microsoft-s-cyberpunk-2077-themed-xbox.md
- content/longboard/i-ran-the-white-house-pandemic-office-trump-closed-it.md
- content/longboard/i-took-the-world-s-first-20-hour-flight-here-s-what-it-did-to-me.md
- content/longboard/ibm-smacks-down-google-on-it-s-claim-around-quantum-computing.md
- content/longboard/in-u-s-library-visits-outpaced-trips-to-movies-in-2019.md
- content/longboard/inside-delta-s-command-center-the-week-the-coronavirus-devastated-the-airline-industry.md
- content/longboard/is-it-canceled-yet.md
- content/longboard/it-appears-that-mailchimp-purchased-courier-magazine.md
- content/longboard/kickin-it-storey-style.md
- content/longboard/larry-david-master-of-his-quarantine.md
- content/longboard/macos-catalina-users-have-access-to-premium-typography.md
- content/longboard/mailchimp-created-a-website-to-showcase-short-films-set-to-debut-during-sxsw.md
- content/longboard/mls-is-back.md
- content/longboard/national-park-illustrations-based-upon-their-worst-review.md
- content/longboard/nonwhites-and-hispanics-were-a-majority-of-people-under-age-16-in-2019-an-expected-demographic-shift-that-will-grow-over-the-coming-decades..md
- content/longboard/professional-wisdom-from-one-of-the-best-enterprise-grade-senior-designers-i-know.md
- content/longboard/python-movin-on-up.md
- content/longboard/rip-the-outline.md
- content/longboard/senet-is-an-all-new-independent-print-magazine-about-the-craft-creativity-and-community-of-board-gaming..md
- content/longboard/she-designs-books-celebrates-two-years-of-recognizing-women-designers-working-in-book-publishing-with-a-special-exhibition-at-type-directors-club.md
- content/longboard/solari-boards-the-disappearing-sound-of-airports.md
- content/longboard/stories-of-people-who-are-racing-to-save-us.md
- content/longboard/studio-ghibli-created-backgrounds-for-use-on-zoom.md
- content/longboard/take-it-from-someone-who-couldn-t-go-outside.md
- content/longboard/the-2020-eisner-awards-nominees.md
- content/longboard/the-fifty-most-important-websites-of-all-time.md
- content/longboard/the-french-dispatch.md
- content/longboard/the-grass-is-not-hot-lava.md
- content/longboard/the-highlighter-of-1484.md
- content/longboard/the-matter-of-collaborative-costs..md
- content/longboard/the-publishing-playbook.md
- content/longboard/the-towers-of-ladakh..md
- content/longboard/the-type-directors-club-is-dead.md
- content/longboard/the-united-states-is-not-headed-towards-a-new-great-depression.md
- content/longboard/there-is-no-plan-to-return-to-normal.md
- content/longboard/this-is-not-an-endorsement-of-arson.md
- content/longboard/typographic-illusions.md
- content/longboard/under-consideration-takes-a-look-at-the-identity-for-think-2020-ibm-s-annual-technology-and-insights-conference.md
- content/longboard/using-a-dslr-as-a-webcam.md
- content/longboard/what-happens-to-a-society-that-loses-its-capacity-for-awe-and-wonder-at-things-to-come.md
- content/longboard/what-seattle-has-looked-like-under-the-stay-at-home-order.md
- content/longboard/yours-truly-on-how-to-facilitate-a-successful-remote-workshop.md
