---
label: Longboard
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Link title, appears on the home page list
- name: target_url
  type: text
  config:
    required: true
  label: Target URL
  description: External URL this post will link to.
- name: date
  type: datetime
  description: Publish date
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  label: Date
- name: tags
  type: tag_list
  default: []
  label: Tags
pages:
- content/longboard/000000-lives-matter-1.md
- content/longboard/000000-lives-matter.md
- content/longboard/2021-logo-trend-report.md
- content/longboard/500-versus-16-steak-dinner.md
- content/longboard/a-comprehensive-look-at-the-energy-crisis-nobody-saw-coming.md
- content/longboard/a-conversation-with-the-graphic-designer-who-until-his-death-at-91-was-still-thinking-about-how-his-craft-could-help-his-beleaguered-city..md
- content/longboard/a-farewell-to-the-quick-brown-fox..md
- content/longboard/a-live-feed-from-the-iceland-volcano.md
- content/longboard/a-new-hope-for-rss.md
- content/longboard/a-new-issue-of-an-old-zine.md
- content/longboard/a-state-by-state-guide-to-voting-in-the-age-of-covid-19.md
- content/longboard/a-typeface-created-to-support-local-languages.md
- content/longboard/according-to-20-000-creatives-brainstorming-is-a-giant-waste-of-time.md
- content/longboard/after-three-years-of-data-analysis-the-discrepancy-remains-a-potential-sign-of-new-physics.md
- content/longboard/amazon-s-ring-is-the-largest-civilian-surveillance-network-the-us-has-ever-seen.md
- content/longboard/an-event-apart-just-launched-its-first-virtual-event-human-centered-design.md
- content/longboard/an-oral-history-behind-the-star-trek-episode-that-saved-next-generation.md
- content/longboard/an-oral-history-of-the-birth-of-responsive-web-design.md
- content/longboard/an-oral-history-of-turkeys-away-the-best-episode-of-wkrp-in-cincinnati.md
- content/longboard/apple-card-disabled-my-icloud-app-store-and-apple-id-accounts.md
- content/longboard/apple-keynote-animation-masterclass.md
- content/longboard/atari-is-now-a-brand-of-hotels.md
- content/longboard/behind-the-decks.md
- content/longboard/being-bill-murray..md
- content/longboard/beowulf-a-new-translation.md
- content/longboard/blacklight.md
- content/longboard/blank-slate.md
- content/longboard/block-studio-is-insane.md
- content/longboard/bmw-legends.md
- content/longboard/boba-fett-will-appear-in-the-next-season-of-the-mandalorian.md
- content/longboard/bookshop-allows-you-to-shop-independent-book-stores-online.md
- content/longboard/boot-camp-will-not-work-on-apple-silicon-based-macs..md
- content/longboard/brand-new-is-switching-to-a-subscription-model.md
- content/longboard/break-down-the-walls..md
- content/longboard/business-is-not-a-sport.md
- content/longboard/byron-s-last-mountain-bike-ride-of-the-season.md
- content/longboard/can-i-use-fonts-and-stock-art-products-in-an-nft-non-fungible-token.md
- content/longboard/convincing-looking-90s-fonts-in-modern-browsers.md
- content/longboard/covid-19-seems-to-have-changed-lifestyles-for-good..md
- content/longboard/dave-s-quintessential-blogging-mistake.md
- content/longboard/dave-switches-back-to-mac.md
- content/longboard/david-carson-has-a-masterclass.md
- content/longboard/democracy-by-mail.md
- content/longboard/democracy-is-in-retreat.md
- content/longboard/design-books-by-womxn-people-of-color.md
- content/longboard/diamond-comics-distributors-announced-that-it-will-cease-shipping-new-comics-as-of-this-week.md
- content/longboard/eight-space-opera-books-to-read-while-waiting-for-the-next-season-of-the-mandalorian.md
- content/longboard/es-bueno-is-back.md
- content/longboard/european-super-league-looks-to-be-here-to-stay.md
- content/longboard/every-jurassic-park-dinosaur-illustrated-with-modern-science.md
- content/longboard/every-zoom-security-and-privacy-flaw-so-far-and-what-you-can-do-to-protect-yourself.md
- content/longboard/everyone-needs-some-ted-lasso-in-their-lives.md
- content/longboard/faa-has-cleared-amazon-to-use-drones-for-delivery.md
- content/longboard/facebook-is-a-doomsday-machine.md
- content/longboard/five-typography-adjacent-books-for-indoor-times.md
- content/longboard/fixing-a-broken-apple-pencil.md
- content/longboard/flat-white-world.md
- content/longboard/fontshop-is-celebrating-30-years-in-business-with-a-30-discount-on-particular-font-families.md
- content/longboard/for-one-day-the-nhl-arena-moved-to-the-mountains.md
- content/longboard/four-principles-from-a-working-mom-worth-applying-to-all-of-our-lives.md
- content/longboard/fwa-is-up-for-sale.md
- content/longboard/ghostbusters-ecto-1.md
- content/longboard/good-guys-how-men-can-be-better-allies-for-women-in-the-workplace.md
- content/longboard/google-is-bringing-stadia-to-ios.md
- content/longboard/google-orders-employees-to-work-from-home-until-july-2021.md
- content/longboard/google-workers-to-form-a-union.md
- content/longboard/gowalla-is-back.md
- content/longboard/graphic-design-is-usually-used-to-amplify-a-desired-effect.as-such-when-successful-typography-changes-perception.this-is-not-easy-to-quantify-but-we-know-that-it-happens..md
- content/longboard/halt-and-catch-fire-syllabus.md
- content/longboard/helping-greg-story-get-airbag-industries-off-movable-type-and-onto-a-better-publishing-stack.md
- content/longboard/hiding-ideas.md
- content/longboard/hoefler-co-goes-on-the-campaign-trail.md
- content/longboard/hotels-of-pyongyang.md
- content/longboard/how-airships-could-return-to-our-crowded-skies.md
- content/longboard/how-do-you-communicate-to-people-ten-thousand-years-from-now.md
- content/longboard/how-qanon-is-tearing-families-apart.md
- content/longboard/how-the-journalism-competition-bill-would-allow-publishers-in-the-u.s.to-collectively-bargain-with-facebook-and-google.md
- content/longboard/how-to-be-the-best.md
- content/longboard/how-to-citizen-with-baratunde.md
- content/longboard/how-to-hug-during-a-pandemic.md
- content/longboard/how-to-make-a-chess-set..md
- content/longboard/how-to-overcome-writer-s-block.md
- content/longboard/how-to-play-dungeons-dragons-and-other-pen-and-paper-games-without-leaving-home.md
- content/longboard/how-to-take-a-decent-photo-of-your-own-shoes-with-a-combination-of-iphone-and-apple-watch.md
- content/longboard/i-for-one-take-solace-in-knowing-we-re-not-seeing-something-new..md
- content/longboard/i-m-going-to-need-microsoft-s-cyberpunk-2077-themed-xbox.md
- content/longboard/i-m-not-yet-ready-to-abandon-the-possibility-of-america..md
- content/longboard/i-ran-the-white-house-pandemic-office-trump-closed-it.md
- content/longboard/i-took-the-world-s-first-20-hour-flight-here-s-what-it-did-to-me.md
- content/longboard/ibm-smacks-down-google-on-it-s-claim-around-quantum-computing.md
- content/longboard/if-your-blog-is-on-our-modern-platform-it-got-much-faster-this-week..md
- content/longboard/imagine-if-news-wasn-t-there..md
- content/longboard/in-u-s-library-visits-outpaced-trips-to-movies-in-2019.md
- content/longboard/inside-delta-s-command-center-the-week-the-coronavirus-devastated-the-airline-industry.md
- content/longboard/inside-the-font-factory-meet-the-man-who-shapes-the-world-s-letters.md
- content/longboard/internet-explorer-is-dead.md
- content/longboard/is-it-canceled-yet.md
- content/longboard/issues-of-design-discourse-past.md
- content/longboard/it-appears-that-mailchimp-purchased-courier-magazine.md
- content/longboard/it-s-not-about-the-struggle-it-s-about-what-you-learned.md
- content/longboard/it-s-official-the-writers-at-the-verge-have-no-sense-of-humor.md
- content/longboard/japan-is-working-to-build-a-floating-spaceport-in-tokyo..md
- content/longboard/kickin-it-storey-style.md
- content/longboard/know-the-culture-before-taking-the-job.md
- content/longboard/languishing-the-dominant-emotion-of-2021..md
- content/longboard/larry-david-master-of-his-quarantine.md
- content/longboard/literal-is-a-new-community-for-readers.md
- content/longboard/macos-catalina-users-have-access-to-premium-typography.md
- content/longboard/magculture-live-2020.md
- content/longboard/mailchimp-created-a-website-to-showcase-short-films-set-to-debut-during-sxsw.md
- content/longboard/mailchimp-s-2020-annual-report-not-a-fan.md
- content/longboard/mark-zeros-out-his-place-on-the-internet.md
- content/longboard/medium-brings-back-the-blog-roll.md
- content/longboard/medium-has-acquired-a-social-digital-book-platform-called-glose.md
- content/longboard/millennials-and-gen-z-want-to-buy-products-and-services-that-reflect-their-beliefs.md
- content/longboard/mls-is-back.md
- content/longboard/mmm-is-geocities-on-crack.md
- content/longboard/monocle-s-digital-decency-manifesto.md
- content/longboard/ms.jen-has-reservations-about-reservations..md
- content/longboard/my-secret-weapon-for-helping-executives-understand-the-value-of-design.-1.md
- content/longboard/my-secret-weapon-for-helping-executives-understand-the-value-of-design..md
- content/longboard/national-park-illustrations-based-upon-their-worst-review.md
- content/longboard/navigating-make-it-pop-design-requests.md
- content/longboard/naz-is-writing-again.md
- content/longboard/no-magic-in-riso.md
- content/longboard/nonwhites-and-hispanics-were-a-majority-of-people-under-age-16-in-2019-an-expected-demographic-shift-that-will-grow-over-the-coming-decades..md
- content/longboard/nope-the-european-super-league-is-gone.md
- content/longboard/once-vaccinated-are-you-free-to-hang-out-with-other-people.md
- content/longboard/one-year-of-daily-co-working.md
- content/longboard/our-civics-test.md
- content/longboard/phil-gilbert-passes-the-ibm-design-baton.md
- content/longboard/plus-equals.md
- content/longboard/professional-wisdom-from-one-of-the-best-enterprise-grade-senior-designers-i-know.md
- content/longboard/puck-yeah.md
- content/longboard/python-movin-on-up.md
- content/longboard/quartz-comes-in-hot-with-news-that-culture-trumps-tools.md
- content/longboard/readers-don-t-always-know-what-editorial-means-and-the-word-itself-has-multiple-uses..md
- content/longboard/reading-design.md
- content/longboard/regarding-design-details-of-the-apple-watch.md
- content/longboard/rest-in-peace-steven-spurrier.md
- content/longboard/rip-the-outline.md
- content/longboard/scrappychat-is-a-thing-and-it-finally-has-a-name.md
- content/longboard/senet-is-an-all-new-independent-print-magazine-about-the-craft-creativity-and-community-of-board-gaming..md
- content/longboard/serbia-showing-the-world-how-it-s-supposed-to-work.md
- content/longboard/she-designs-books-celebrates-two-years-of-recognizing-women-designers-working-in-book-publishing-with-a-special-exhibition-at-type-directors-club.md
- content/longboard/solari-boards-the-disappearing-sound-of-airports.md
- content/longboard/spot-on-commentary-against-current-branding-practices-in-major-league-soccer.md
- content/longboard/stories-of-people-who-are-racing-to-save-us.md
- content/longboard/studio-ghibli-created-backgrounds-for-use-on-zoom.md
- content/longboard/supersonic-travel-is-making-a-comeback.md
- content/longboard/ta-nehisi-coates-exit-interview.md
- content/longboard/take-it-from-someone-who-couldn-t-go-outside.md
- content/longboard/the-148-congress-persons-who-voted-to-overturn-the-federal-election.md
- content/longboard/the-2020-eisner-awards-nominees.md
- content/longboard/the-animaniacs-reboot-we-all-desperately-need.md
- content/longboard/the-art-behind-hunter-s.thompson-s-1970-political-campaign.md
- content/longboard/the-best-monospaced-typeface-you-re-not-using.md
- content/longboard/the-best-non-alcoholic-drinks.md
- content/longboard/the-data-show-democracy-is-thriving.md
- content/longboard/the-eight-secrets-to-a-fairly-fulfilled-life.md
- content/longboard/the-fed-up-chef..md
- content/longboard/the-fifty-most-important-websites-of-all-time.md
- content/longboard/the-french-dispatch.md
- content/longboard/the-grass-is-not-hot-lava.md
- content/longboard/the-high-life.md
- content/longboard/the-highlighter-of-1484.md
- content/longboard/the-hill-we-climb..md
- content/longboard/the-jerry-seinfeld-guide-to-writing.md
- content/longboard/the-matter-of-collaborative-costs..md
- content/longboard/the-membership-guide.md
- content/longboard/the-modern-brand-os.md
- content/longboard/the-next-best-american-author-dies-before-his-first-book-is-published.md
- content/longboard/the-publishing-playbook.md
- content/longboard/the-story-behind-the-brand-development-of-seattle-kraken.md
- content/longboard/the-three-click-rule-is-dead.md
- content/longboard/the-towers-of-ladakh..md
- content/longboard/the-type-directors-club-is-dead.md
- content/longboard/the-united-states-is-not-headed-towards-a-new-great-depression.md
- content/longboard/the-winner-loser-gap..md
- content/longboard/the-year-in-search-magazine.md
- content/longboard/there-is-no-plan-to-return-to-normal.md
- content/longboard/thirteen-ways-of-looking-at-a-typeface.md
- content/longboard/this-is-not-an-endorsement-of-arson.md
- content/longboard/this-shit-is-complex..md
- content/longboard/time-dust-off-independents-day-and-prepare-for-2.0.md
- content/longboard/touch-screen-macs.md
- content/longboard/typographic-illusions.md
- content/longboard/under-consideration-takes-a-look-at-the-identity-for-think-2020-ibm-s-annual-technology-and-insights-conference.md
- content/longboard/use-sony-cameras-as-a-webcam-without-hardware-conversion.md
- content/longboard/using-a-dslr-as-a-webcam.md
- content/longboard/verizon-sold-yahoo-and-aol.md
- content/longboard/we-act-and-behave-like-a-brand-new-restaurant-every-year..md
- content/longboard/we-lost-our-studio-twice.but-not-our-community.md
- content/longboard/what-happens-to-a-society-that-loses-its-capacity-for-awe-and-wonder-at-things-to-come.md
- content/longboard/what-i-learned-publishing-200-blog-posts..md
- content/longboard/what-s-a-newspaper-presidential-endorsement-worth.md
- content/longboard/what-s-going-on-at-50.md
- content/longboard/what-seattle-has-looked-like-under-the-stay-at-home-order.md
- content/longboard/winter-is-coming-covid-style.md
- content/longboard/wired-makes-the-case-for-ditching-google-chrome.md
- content/longboard/wired-rates-thirteen-electric-bikes.md
- content/longboard/wordpress-is-a-mess..md
- content/longboard/writing-built-the-united-states.md
- content/longboard/you-should-have-your-own-place-in-the-internet..md
- content/longboard/yours-truly-on-how-to-facilitate-a-successful-remote-workshop.md
