---
label: Longboard
hide_body: false
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
  description: Link title, appears on the home page list
- name: target_url
  type: text
  config:
    required: true
  label: Target URL
  description: External URL this post will link to.
- name: date
  type: datetime
  description: Publish date
  config:
    required: true
    date_format: 
    time_format: 
    display_utc: false
  label: Date
pages:
- content/longboard/another-external-link-goes-here.md
