---
label: Post
hide_body: false
fields:
- name: date
  type: datetime
  label: Date
  description: Publish date
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  hidden: false
